apiVersion: batch/v1
kind: Job
metadata:
  namespace: jobs
  generateName: sample-job-team-a-
  annotations:
    kueue.x-k8s.io/queue-name: lq-team-a # Point to the LocalQueue
spec:
  ttlSecondsAfterFinished: 60 # Job will be deleted after 60 seconds
  template:
    metadata:
      annotations:
        gke-gcsfuse/volumes: "true"
    spec:
      serviceAccountName: k8s-sa-cluster
      containers:
      - name: writer
        image: busybox
        command:
          - "/bin/sh"
          - "-c"
          - touch /input/test && echo $(date) >> /input/test && sleep 10
        volumeMounts:
        - name: gcs-fuse-csi-ephemeral-input
          mountPath: /input
      - name: reader
        image: busybox
        command:
          - "/bin/sh"
          - "-c"
          - sleep 10 && cat /input/test
        volumeMounts:
        - name: gcs-fuse-csi-ephemeral-input
          mountPath: /input
          readOnly: true
      volumes:
      - name: gcs-fuse-csi-ephemeral-input
        csi:
          driver: gcsfuse.csi.storage.gke.io
          volumeAttributes:
            bucketName: gcs-testtest-431919-gcp-test-input
      restartPolicy: Never
  backoffLimit: 1