steps:
- id: 'repoBuildConfirmation'
  name: 'alpine'
  entrypoint: 'sh'
  dir: /workspace
  args:
  - '-c'
  - |
      echo "***********************"
      echo "***********************"
      echo "Running Container Build"
      echo "***********************"
      echo "***********************"
      echo ""
      echo "$_PROJECT_ID"
      echo "$LOCATION"
      echo "$_ARTIFACT_REPO_NAME"
      echo "$_IMAGE_NAME"
      echo "$_IMAGE_VERSION"
      echo ""
      echo "***********************"

- id: 'dockerBuild'
  name: 'gcr.io/cloud-builders/docker'
  dir: /workspace
  args: [ 'build',
    '-t',
    '${_LOCATION}-docker.pkg.dev/${_PROJECT_ID}/${_ARTIFACT_REPO_NAME}/${_IMAGE_NAME}:${_IMAGE_VERSION}',
    '.' ]

images:
- '${_LOCATION}-docker.pkg.dev/${_PROJECT_ID}/${_ARTIFACT_REPO_NAME}/${_IMAGE_NAME}:${_IMAGE_VERSION}'

# options:
#   logging: CLOUD_LOGGING_ONLY

substitutions:
  _PROJECT_ID: ''
  _ARTIFACT_REPO_NAME: 'repo-batch-jobs'
  _IMAGE_NAME: 'ffmpeg-api'
  _IMAGE_VERSION: 'v0.0.1'
  _LOCATION: 'us-central1'