apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  name: cluster-queue-a
spec:
  namespaceSelector: {} # Available to all namespaces
  # cohort: "team-ab"
  queueingStrategy: BestEffortFIFO # Default queueing strategy
  resourceGroups:
  - coveredResources: ["cpu", "memory", "nvidia.com/gpu", "ephemeral-storage", "cloud.google.com/pod-slots"]
    flavors:
    - name: "default-flavor"
      resources:
      - name: "cpu"
        nominalQuota: 32
        # borrowingLimit: 20
      - name: "memory"
        nominalQuota: 128Gi
      - name: "nvidia.com/gpu"
        nominalQuota: 2
      - name: "ephemeral-storage"
        nominalQuota: 200Gi
      - name: "cloud.google.com/pod-slots"
        nominalQuota: 10
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  name: cluster-queue-b
spec:
  namespaceSelector: {} # Available to all namespaces
  # cohort: "team-ab"
  queueingStrategy: BestEffortFIFO # Default queueing strategy
  resourceGroups:
  - coveredResources: ["cpu", "memory", "nvidia.com/gpu", "ephemeral-storage", "cloud.google.com/pod-slots"]
    flavors:
    - name: "spot"
      resources:
      - name: "cpu"
        nominalQuota: 160
        # lendingLimit: 10
      - name: "memory"
        nominalQuota: 640Gi
      - name: "nvidia.com/gpu"
        nominalQuota: 10
      - name: "ephemeral-storage"
        nominalQuota: 1000Gi
      - name: "cloud.google.com/pod-slots"
        nominalQuota: 100
    - name: "default-flavor"
      resources:
      - name: "cpu"
        nominalQuota: 100
        # lendingLimit: 10
      - name: "memory"
        nominalQuota: 100Gi
      - name: "nvidia.com/gpu"
        nominalQuota: 10
      - name: "ephemeral-storage"
        nominalQuota: 500Gi
      - name: "cloud.google.com/pod-slots"
        nominalQuota: 100